dnl Process this file with autoconf to produce a configure script.

dnl Include external macro definitions before the AC_INIT to also remove
dnl comments starting with # and empty newlines from the included files.
dnl ----------------------------------------------------------------------------
m4_include([build/ax_check_compile_flag.m4])
m4_include([build/ax_func_which_gethostbyname_r.m4])
m4_include([build/ax_gcc_func_attribute.m4])

m4_include([build/libtool.m4])
m4_include([build/ltoptions.m4])
m4_include([build/ltsugar.m4])
m4_include([build/ltversion.m4])
m4_include([build/lt~obsolete.m4])

m4_include([build/php_cxx_compile_stdcxx.m4])
m4_include([build/php.m4])
m4_include([build/pkg.m4])
m4_include([TSRM/threads.m4])
m4_include([Zend/Zend.m4])

dnl Basic autoconf initialization, generation of config.nice.
dnl ----------------------------------------------------------------------------

AC_PREREQ([2.68])
AC_INIT([BLOA LANGUAGE],[0.1.0],[https://github.com/bloa-lang/bloa-src/issues],[bloa],[https://github.com/bloa-lang/bloa-src])
AC_CONFIG_SRCDIR([main/php_version.h])
AC_CONFIG_MACRO_DIR([build])
AC_CONFIG_AUX_DIR([build])
AC_PRESERVE_HELP_ORDER

PHP_CONFIG_NICE([config.nice])

PHP_CANONICAL_HOST_TARGET

AC_CONFIG_HEADERS([main/php_config.h])

AH_TOP([
#ifndef PHP_CONFIG_H
#define PHP_CONFIG_H

#if defined(__GNUC__) && __GNUC__ >= 4
# define ZEND_API __attribute__ ((visibility("default")))
# define ZEND_DLEXPORT __attribute__ ((visibility("default")))
#else
# define ZEND_API
# define ZEND_DLEXPORT
#endif

#define ZEND_DLIMPORT
])
AH_BOTTOM([
#include <stdlib.h>

#ifdef HAVE_SYS_TYPES_H
# include <sys/types.h>
#endif

#ifdef HAVE_SYS_SELECT_H
#include <sys/select.h>
#endif

#include <string.h>

#endif /* PHP_CONFIG_H */
])

ac_IFS=$IFS; IFS="."
set $(echo AC_PACKAGE_VERSION | "${SED}" 's/\([[0-9\.]]*\)\(.*\)/\1\.\2/')
IFS=$ac_IFS
PHP_MAJOR_VERSION=[0]
PHP_MINOR_VERSION=[1]
PHP_RELEASE_VERSION=[0]
dnl Allow overriding PHP_EXTRA_VERSION through the homonymous env var
AC_ARG_VAR([PHP_EXTRA_VERSION],
  [Extra PHP version label suffix, e.g. '-dev', 'rc1', '-acme'])dnl
AS_VAR_IF([PHP_EXTRA_VERSION],, [PHP_EXTRA_VERSION=[$]4])
PHP_VERSION="$PHP_MAJOR_VERSION.$PHP_MINOR_VERSION.$PHP_RELEASE_VERSION$PHP_EXTRA_VERSION"
PHP_VERSION_ID=$(expr [$]PHP_MAJOR_VERSION \* 10000 + [$]PHP_MINOR_VERSION \* 100 + [$]PHP_RELEASE_VERSION)

dnl Allow version values to be used in Makefile.
PHP_SUBST([PHP_MAJOR_VERSION])
PHP_SUBST([PHP_MINOR_VERSION])
PHP_SUBST([PHP_RELEASE_VERSION])
PHP_SUBST([PHP_EXTRA_VERSION])

dnl Setting up the PHP version based on the information above.
dnl ----------------------------------------------------------------------------

echo "/* automatically generated by configure */" > php_version.h.new
echo "/* edit configure.ac to change version number */" >> php_version.h.new
echo "#define PHP_MAJOR_VERSION $PHP_MAJOR_VERSION" >> php_version.h.new
echo "#define PHP_MINOR_VERSION $PHP_MINOR_VERSION" >> php_version.h.new
echo "#define PHP_RELEASE_VERSION $PHP_RELEASE_VERSION" >> php_version.h.new
echo "#define PHP_EXTRA_VERSION \"$PHP_EXTRA_VERSION\"" >> php_version.h.new
echo "#define PHP_VERSION \"$PHP_VERSION\"" >> php_version.h.new
echo "#define PHP_VERSION_ID $PHP_VERSION_ID" >> php_version.h.new
cmp php_version.h.new $srcdir/main/php_version.h >/dev/null 2>&1
if test $? -ne 0 ; then
  rm -f $srcdir/main/php_version.h && mv php_version.h.new $srcdir/main/php_version.h && \
  echo 'Updated main/php_version.h'
else
  rm -f php_version.h.new
fi

dnl Settings we want to make before the checks.
dnl ----------------------------------------------------------------------------

PHP_INIT_BUILD_SYSTEM

dnl Because 'make install' is often performed by the superuser, we create the
dnl libs subdirectory as the user who configures PHP. Otherwise, the current
dnl user will not be able to delete libs or the contents of libs.

$php_shtool mkdir -p libs
rm -f libs/*

dnl Checks for programs.
dnl ----------------------------------------------------------------------------

PKG_PROG_PKG_CONFIG
AC_PROG_CC([cc gcc])
PHP_DETECT_ICC
PHP_DETECT_SUNCC

dnl AC_PROG_CC_C99 is obsolete with autoconf >= 2.70 yet necessary for <= 2.69.
m4_version_prereq([2.70],,[AC_PROG_CC_C99])
AC_PROG_CPP
AC_USE_SYSTEM_EXTENSIONS
AC_PROG_LN_S

AS_VAR_IF([cross_compiling], [yes],
  [AC_CHECK_PROGS([BUILD_CC], [gcc clang c99 c89 cc cl], [none])
    AC_MSG_CHECKING([for native build C compiler])
    AC_MSG_RESULT([$BUILD_CC])],
  [BUILD_CC=$CC])

dnl The macro AC_PROG_CC_C99 sets the shell variable ac_cv_prog_cc_c99 to 'no'
dnl if the compiler does not support C99.i.e. does not support any of _Bool,
dnl flexible arrays, inline, long long int, mixed code and declarations,
dnl named initialization of structs, restrict, varargs macros, variable
dnl declarations in for loops and variable length arrays.
dnl
dnl https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/C-Compiler.html
if test "$ac_cv_prog_cc_c99" = no; then
  AC_MSG_ERROR([C compiler would not accept C99 code])
fi

dnl Support systems with system libraries in e.g. /usr/lib64.
PHP_ARG_WITH([libdir],
  [for system library directory],
  [AS_HELP_STRING([--with-libdir=NAME],
    [Look for libraries in .../NAME rather than .../lib])],
  [lib],
  [no])

PHP_ARG_ENABLE([rpath],
  [whether to enable runpaths],
  [AS_HELP_STRING([--disable-rpath],
    [Disable passing additional runtime library search paths])],
  [yes],
  [no])

dnl Check for -R, etc. switch.
PHP_RUNPATH_SWITCH

dnl Checks for some support/generator progs.
PHP_PROG_BISON([3.0.0])
PHP_PROG_RE2C([1.0.3], [--no-generation-date -W])
dnl Find installed PHP. Minimum supported version for gen_stub.php is PHP 8.1.
PHP_PROG_PHP([8.1])

PHP_ARG_ENABLE([re2c-cgoto],
  [whether to enable computed goto extension with re2c],
  [AS_HELP_STRING([--enable-re2c-cgoto],
    [Enable re2c -g flag to optimize conditional jumps using computed goto
    extension, if supported by the compiler])],
  [no],
  [no])

AS_VAR_IF([PHP_RE2C_CGOTO], [no],,
[AC_CACHE_CHECK([whether re2c -g works], [php_cv_have_re2c_cgoto],
  [AC_COMPILE_IFELSE([AC_LANG_SOURCE([[
int main(void)
{
label1:
  ;
label2:
  ;
  static void *adr[] = { &&label1, &&label2 };
  goto *adr[0];
  return 0;
}]])],
  [php_cv_have_re2c_cgoto=yes],
  [php_cv_have_re2c_cgoto=no])])
AS_VAR_IF([php_cv_have_re2c_cgoto], [yes],
  [AS_VAR_APPEND([RE2C_FLAGS], [" -g"])])
])

dnl Platform-specific compile settings.
dnl ----------------------------------------------------------------------------

dnl See bug #28605
case $host_cpu in
  alpha*)
    if test "$GCC" = "yes"; then
      CFLAGS="$CFLAGS -mieee"
    else
      CFLAGS="$CFLAGS -ieee"
    fi
    ;;
  sparc*)
    if test "$SUNCC" = "yes"; then
      CFLAGS="$CFLAGS -xmemalign=8s"
    fi
    ;;
esac

dnl See https://github.com/php/php-src/issues/14140
AX_CHECK_COMPILE_FLAG([-ffp-contract=off], [CFLAGS="$CFLAGS -ffp-contract=off"])

dnl Mark symbols hidden by default if the compiler (for example, gcc >= 4)
dnl supports it. This can help reduce the binary size and startup time.
AX_CHECK_COMPILE_FLAG([-fvisibility=hidden],
                       [CFLAGS="$CFLAGS -fvisibility=hidden"])

dnl to disable executable stack on haiku due
dnl to missing elf .note.GNU-stack part
case $host_alias in
  *haiku*)
    LDFLAGS="$LDFLAGS -Wl,-z,noexecstack"
    ;;
  *solaris*)
    CPPFLAGS="$CPPFLAGS -D_POSIX_PTHREAD_SEMANTICS"
    ;;
  *hpux*)
    if test "$GCC" = "yes"; then
      CPPFLAGS="$CPPFLAGS -D_XOPEN_SOURCE_EXTENDED"
    fi
    ;;
esac

dnl Disable PIC mode by default where it is known to be safe to do so, to avoid
dnl the performance hit from the lost register.
AC_MSG_CHECKING([whether to force non-PIC code in shared modules])
case $host_alias in
  i?86-*-linux*|i?86-*-freebsd*)
    if test "${enable_pic+set}" != "set" || test "$enable_pic" = "no"; then
      enable_pic=no
      AC_MSG_RESULT([yes])
    else
      AC_MSG_RESULT([no])
    fi
    ;;
  *)
    AC_MSG_RESULT([no])
    ;;
esac

dnl Detect C library.
PHP_C_STANDARD_LIBRARY
AS_VAR_IF([php_cv_c_standard_library], [musl],
  [AC_DEFINE([__MUSL__], [1], [Define to 1 when using musl libc.])])

dnl Add _GNU_SOURCE compile definition because the php_config.h with definitions
dnl by AC_USE_SYSTEM_EXTENSIONS might be included after the system headers which
dnl require extensions to C and POSIX.
AS_VAR_APPEND([CPPFLAGS], [" -D_GNU_SOURCE"])

PTHREADS_CHECK
PHP_HELP_SEPARATOR([SAPI modules:])
PHP_SHLIB_SUFFIX_NAMES
PHP_BUILD_PROGRAM
PHP_SAPI=none

dnl SAPI configuration.
dnl ----------------------------------------------------------------------------

dnl Paths to the targets are relative to the build directory.
SAPI_LIBNAME=libphp
SAPI_LIBNAME_SHARED=$SAPI_LIBNAME.[]$SHLIB_DL_SUFFIX_NAME
SAPI_LIBNAME_STATIC=$SAPI_LIBNAME.a
SAPI_SHARED=libs/$SAPI_LIBNAME_SHARED
SAPI_STATIC=libs/$SAPI_LIBNAME_STATIC
SAPI_LIBTOOL=libphp.la

PHP_CONFIGURE_PART([Configuring SAPI modules])

esyscmd(./build/config-stubs sapi)

dnl Show which main SAPI was selected.
AC_MSG_CHECKING([for chosen SAPI module])
AC_MSG_RESULT([$PHP_SAPI])

dnl Show which binaries were selected.
AC_MSG_CHECKING([for executable SAPI binaries])
AS_VAR_IF([PHP_BINARIES],,
  [AC_MSG_RESULT([none])],
  [AC_MSG_RESULT([$PHP_BINARIES])])

dnl Exit early.
AS_VAR_IF([PHP_INSTALLED_SAPIS],, [AC_MSG_ERROR([Nothing to build.])])

dnl Add POSIX threads compilation and linker flags when thread safety is enabled
dnl with either the '--enable-zts' configure option or automatically enabled by
dnl PHP SAPIs. For example, Apache SAPI.
AS_VAR_IF([enable_zts], [yes], [
  if test -n "$ac_cv_pthreads_lib"; then
    LIBS="$LIBS -l$ac_cv_pthreads_lib"
  fi
  if test -n "$ac_cv_pthreads_cflags"; then
    CFLAGS="$CFLAGS $ac_cv_pthreads_cflags"
  fi

  PTHREADS_FLAGS
])

dnl Starting system checks.
dnl ----------------------------------------------------------------------------

PHP_CONFIGURE_PART([Running system checks])

dnl Find sendmail binary.
PHP_PROG_SENDMAIL

dnl Check whether the system uses EBCDIC (not ASCII) as its native codeset.
PHP_EBCDIC

dnl Check whether the system byte ordering is bigendian.
PHP_C_BIGENDIAN

dnl Check whether writing to stdout works.
PHP_TEST_WRITE_STDOUT

dnl Check for /usr/pkg/{lib,include} which is where NetBSD puts binary and
dnl source packages. This should be harmless on other OSs.
if test -d /usr/pkg/include && test -d /usr/pkg/lib; then
   CPPFLAGS="$CPPFLAGS -I/usr/pkg/include"
   LDFLAGS="$LDFLAGS -L/usr/pkg/lib"
fi
test -d /usr/ucblib && PHP_ADD_LIBPATH([/usr/ucblib])

dnl First, library checks.
dnl ----------------------------------------------------------------------------

AC_SEARCH_LIBS([socket], [socket network])

AC_CHECK_FUNCS([socketpair],,
  [AC_SEARCH_LIBS([socketpair], [socket network],
    [AC_DEFINE([HAVE_SOCKETPAIR], [1])])])

AC_SEARCH_LIBS([gethostbyaddr], [nsl network])

AC_SEARCH_LIBS([dlopen], [dl],
  [AC_DEFINE([HAVE_LIBDL], [1],
    [Define to 1 if you have the 'dl' library (-ldl).])])

AC_SEARCH_LIBS([sin], [m])

case $host_alias in
  riscv64*)
    PHP_CHECK_FUNC(__atomic_exchange_1, atomic)
    ;;
esac

dnl Solaris/Illumos for process mapping.
AC_SEARCH_LIBS([Pgrab], [proc])

dnl Haiku does not have network api in libc.
AC_SEARCH_LIBS([setsockopt], [network])

dnl Check for openpty. It may require linking against libutil or libbsd.
AC_CHECK_FUNCS([openpty],,
  [AC_SEARCH_LIBS([openpty], [util bsd], [AC_DEFINE([HAVE_OPENPTY], [1])])])

dnl Then headers.
dnl ----------------------------------------------------------------------------

dnl QNX requires unix.h to allow functions in libunix to work properly.
AC_CHECK_HEADERS(m4_normalize([
  dirent.h
  sys/param.h
  sys/types.h
  sys/time.h
  netinet/in.h
  alloca.h
  arpa/inet.h
  arpa/nameser.h
  dns.h
  fcntl.h
  grp.h
  ieeefp.h
  langinfo.h
  linux/sock_diag.h
  poll.h
  pty.h
  pwd.h
  resolv.h
  strings.h
  syslog.h
  sysexits.h
  sys/ioctl.h
  sys/file.h
  sys/mman.h
  sys/mount.h
  sys/poll.h
  sys/resource.h
  sys/select.h
  sys/socket.h
  sys/stat.h
  sys/statfs.h
  sys/statvfs.h
  sys/vfs.h
  sys/sysexits.h
  sys/uio.h
  sys/wait.h
  sys/loadavg.h
  unistd.h
  unix.h
  utime.h
  sys/utsname.h
  sys/ipc.h
  dlfcn.h
  tmmintrin.h
  nmmintrin.h
  wmmintrin.h
  immintrin.h
]),,, [dnl
#ifdef HAVE_SYS_PARAM_H
#include <sys/param.h>
#endif
#ifdef HAVE_SYS_TYPES_H
#include <sys/types.h>
#endif
#ifdef HAVE_SYS_TIME_H
#include <sys/time.h>
#endif
#ifdef HAVE_NETINET_IN_H
#include <netinet/in.h>
#endif
#ifdef HAVE_ARPA_NAMESER_H
#include <arpa/nameser.h>
#endif
])

PHP_FOPENCOOKIE
PHP_BROKEN_GETCWD
AS_VAR_IF([GCC], [yes], [PHP_BROKEN_GCC_STRLEN_OPT])

dnl Detect the headers required to use makedev, major, and minor.
dnl Autoconf <= 2.69 didn't check glibc 2.25 deprecated macros in sys/types.h.
m4_version_prereq([2.70],,[ac_cv_header_sys_types_h_makedev=no])
AC_HEADER_MAJOR

dnl Checks for typedefs, structures, and compiler characteristics.
dnl ----------------------------------------------------------------------------

AC_STRUCT_TIMEZONE

PHP_MISSING_TIME_R_DECL

AC_CHECK_TYPES([struct flock],,,[#include <fcntl.h>])
AC_CHECK_TYPES([socklen_t], [], [], [
  #ifdef HAVE_SYS_TYPES_H
  # include <sys/types.h>
  #endif
  #ifdef HAVE_SYS_SOCKET_H
  # include <sys/socket.h>
  #endif
])

dnl Check stdint types (must be after header check).
PHP_CHECK_STDINT_TYPES

dnl Check GNU C builtins.
PHP_CHECK_BUILTIN([__builtin_clz])
PHP_CHECK_BUILTIN([__builtin_clzl])
PHP_CHECK_BUILTIN([__builtin_clzll])
PHP_CHECK_BUILTIN([__builtin_cpu_init])
PHP_CHECK_BUILTIN([__builtin_cpu_supports])
PHP_CHECK_BUILTIN([__builtin_ctzl])
PHP_CHECK_BUILTIN([__builtin_ctzll])
PHP_CHECK_BUILTIN([__builtin_expect])
PHP_CHECK_BUILTIN([__builtin_frame_address])
PHP_CHECK_BUILTIN([__builtin_saddl_overflow])
PHP_CHECK_BUILTIN([__builtin_saddll_overflow])
PHP_CHECK_BUILTIN([__builtin_smull_overflow])
PHP_CHECK_BUILTIN([__builtin_smulll_overflow])
PHP_CHECK_BUILTIN([__builtin_ssubl_overflow])
PHP_CHECK_BUILTIN([__builtin_ssubll_overflow])
PHP_CHECK_BUILTIN([__builtin_unreachable])
PHP_CHECK_BUILTIN([__builtin_usub_overflow])

dnl Check AVX512
PHP_CHECK_AVX512_SUPPORTS
dnl Check AVX512 VBMI
PHP_CHECK_AVX512_VBMI_SUPPORTS

dnl Check for __alignof__ support in the compiler
AC_CACHE_CHECK([whether the compiler supports __alignof__],
[php_cv_have_alignof],
[AC_COMPILE_IFELSE([AC_LANG_PROGRAM([], [
  int align = __alignof__(int);
  (void)align;
])],
[php_cv_have_alignof=yes],
[php_cv_have_alignof=no])])
AS_VAR_IF([php_cv_have_alignof], [yes],
  [AC_DEFINE([HAVE_ALIGNOF], [1],
    [Define to 1 if the compiler supports '__alignof__'.])])

dnl Check for structure members.
AC_CHECK_MEMBERS([struct tm.tm_gmtoff],,,[#include <time.h>])
AC_CHECK_MEMBERS(m4_normalize([
  struct stat.st_blksize,
  struct stat.st_blocks,
  struct stat.st_rdev
]))

dnl Checks for types.
AC_TYPE_UID_T

dnl Checks for sockaddr_storage and sockaddr.sa_len.
AC_CHECK_TYPES([struct sockaddr_storage],,,[#include <sys/socket.h>])
AC_CHECK_MEMBERS([struct sockaddr.sa_len],,,[#include <sys/socket.h>])

dnl Checks for GCC function attributes on all systems except ones without glibc
dnl Fix for these systems is already included in GCC 7, but not on GCC 6.
dnl
dnl At least some versions of FreeBSD seem to have buggy ifunc support, see
dnl bug #77284. Conservatively don't use ifuncs on FreeBSD prior to version 12.
AS_CASE([$host_alias], [*-*-*android*|*-*-*uclibc*|*-*-*musl*|*openbsd*], [true], [
  if test "$(uname -s 2>/dev/null)" != "FreeBSD" || test "$(uname -U 2>/dev/null)" -ge 1200000; then
    AX_GCC_FUNC_ATTRIBUTE([ifunc])
    AX_GCC_FUNC_ATTRIBUTE([target])
  fi
])

dnl Check for __attribute__ ((__aligned__)) support in the compiler.
PHP_CHECK_VARIABLE_ATTRIBUTE([aligned])

dnl Checks for library functions.
dnl ----------------------------------------------------------------------------

save_CFLAGS="$CFLAGS"
case "$CC" in
  *clang*)
    AX_CHECK_COMPILE_FLAG([-Wno-incompatible-library-redeclaration], [
      CFLAGS="$CFLAGS -Wno-incompatible-library-redeclaration"
    ])
    AX_CHECK_COMPILE_FLAG([-Wno-builtin-declaration-mismatch], [
      CFLAGS="$CFLAGS -Wno-builtin-declaration-mismatch"
    ])
    AX_CHECK_COMPILE_FLAG([-Wno-deprecated-declarations], [
      CFLAGS="$CFLAGS -Wno-deprecated-declarations"
    ])
    ;;
esac

AC_CHECK_FUNCS(m4_normalize([
  alphasort
  asctime_r
  asprintf
  chroot
  ctime_r
  explicit_memset
  fdatasync
  flock
  ftok
  funopen
  gai_strerror
  getcwd
  getgrnam_r
  gethostname
  getloadavg
  getprotobyname
  getprotobynumber
  getpwnam_r
  getpwuid_r
  getrusage
  getservbyname
  getservbyport
  gettimeofday
  getwd
  glob
  gmtime_r
  issetugid
  lchown
  localtime_r
  memcntl
  memfd_create
  memmem
  mempcpy
  memrchr
  memset_explicit
  mkstemp
  mmap
  nice
  nl_langinfo
  poll
  pthread_jit_write_protect_np
  putenv
  reallocarray
  scandir
  setenv
  setitimer
  shutdown
  sigprocmask
  statfs
  statvfs
  std_syslog
  strcasecmp
  strptime
  strtok_r
  symlink
  tzset
  unsetenv
  usleep
  utime
  vasprintf
]))
CFLAGS="$save_CFLAGS"

PHP_ARG_ENABLE([system-glob],
  [whether to use the system glob function],
  [AS_HELP_STRING([--enable-system-glob],
    [Use the system glob function instead of the PHP provided replacement.])],
  [no],
  [no])

AS_VAR_IF([PHP_SYSTEM_GLOB], [yes],
  [AC_DEFINE([PHP_SYSTEM_GLOB], [1],
    [Define to 1 if PHP will use the system glob function instead of php_glob.])])

AC_CHECK_FUNC([inet_ntop],, [AC_MSG_FAILURE([Required inet_ntop not found.])])
AC_CHECK_FUNC([inet_pton],, [AC_MSG_FAILURE([Required inet_pton not found.])])

dnl Check for strerror_r, and if its a POSIX-compatible or a GNU specific version.
AC_FUNC_STRERROR_R

dnl Check for functions inside their belonging headers.
AC_CHECK_HEADER([sys/prctl.h], [AC_CHECK_FUNCS([prctl])])
AC_CHECK_HEADER([sys/procctl.h], [AC_CHECK_FUNCS([procctl])])

AX_FUNC_WHICH_GETHOSTBYNAME_R

dnl Some systems (Solaris 10) do not have nanosleep in libc.
AC_CHECK_FUNCS([nanosleep],,
  [AC_SEARCH_LIBS([nanosleep], [rt], [AC_DEFINE([HAVE_NANOSLEEP], [1])])])

dnl Check for getaddrinfo, should be a better way, but... Also check for working
dnl getaddrinfo.
AC_CACHE_CHECK([for getaddrinfo], [php_cv_func_getaddrinfo],
[AC_LINK_IFELSE([AC_LANG_PROGRAM([#include <netdb.h>],
  [struct addrinfo *g,h;g=&h;getaddrinfo("","",g,&g);])],
  [AC_RUN_IFELSE([AC_LANG_SOURCE([
#include <netdb.h>
#include <sys/types.h>
#include <string.h>
#include <stdlib.h>
#ifndef AF_INET
# include <sys/socket.h>
#endif
int main(void) {
  struct addrinfo *ai, *pai, hints;

  memset(&hints, 0, sizeof(hints));
  hints.ai_flags = AI_NUMERICHOST;

  if (getaddrinfo("127.0.0.1", 0, &hints, &ai) < 0) {
    return 1;
  }

  if (ai == 0) {
    return 1;
  }

  pai = ai;

  while (pai) {
    if (pai->ai_family != AF_INET) {
      /* 127.0.0.1/NUMERICHOST should only resolve ONE way */
      return 1;
    }
    if (pai->ai_addr->sa_family != AF_INET) {
      /* 127.0.0.1/NUMERICHOST should only resolve ONE way */
      return 1;
    }
    pai = pai->ai_next;
  }
  freeaddrinfo(ai);
  return 0;
}
  ])],
  [php_cv_func_getaddrinfo=yes],
  [php_cv_func_getaddrinfo=no],
  [AS_CASE([$host_alias],
    [*linux*|*midipix], [php_cv_func_getaddrinfo=yes],
    [php_cv_func_getaddrinfo=no])])],
[php_cv_func_getaddrinfo=no])])
AS_VAR_IF([php_cv_func_getaddrinfo], [yes],
  [AC_DEFINE([HAVE_GETADDRINFO], [1],
    [Define to 1 if you have the 'getaddrinfo' function.])])

dnl on FreeBSD, copy_file_range() works only with the undocumented flag 0x01000000;
dnl until the problem is fixed properly, copy_file_range() is used only on Linux
AC_CACHE_CHECK([for copy_file_range], [php_cv_func_copy_file_range],
[AC_COMPILE_IFELSE([AC_LANG_SOURCE([
#ifndef __linux__
# error "unsupported platform"
#endif
#ifndef _GNU_SOURCE
# define _GNU_SOURCE
#endif
#include <linux/version.h>
#if LINUX_VERSION_CODE < KERNEL_VERSION(5,3,0)
# error "kernel too old"
#endif
#include <unistd.h>
int main(void)
{
  (void)copy_file_range(-1, 0, -1, 0, 0, 0);
  return 0;
}
])],
[php_cv_func_copy_file_range=yes],
[php_cv_func_copy_file_range=no])
])
AS_VAR_IF([php_cv_func_copy_file_range], [yes],
  [AC_DEFINE([HAVE_COPY_FILE_RANGE], [1],
    [Define to 1 if you have the 'copy_file_range' function.])])

AC_REPLACE_FUNCS([strlcat strlcpy explicit_bzero getopt])
AC_FUNC_ALLOCA
PHP_TIME_R_TYPE

AC_CACHE_CHECK([for aarch64 CRC32 API], [php_cv_func___crc32d],
[AC_LINK_IFELSE([AC_LANG_PROGRAM([
#include <arm_acle.h>
# if defined(__GNUC__)
#  if!defined(__clang__)
#   pragma GCC push_options
#   pragma GCC target ("+nothing+crc")
#  elif defined(__APPLE__)
#   pragma clang attribute push(__attribute__((target("crc"))), apply_to=function)
#  else
#   pragma clang attribute push(__attribute__((target("+nothing+crc"))), apply_to=function)
#  endif
# endif
], [__crc32d(0, 0);])],
[php_cv_func___crc32d=yes],
[php_cv_func___crc32d=no])])
AS_VAR_IF([php_cv_func___crc32d], [yes],
  [AC_DEFINE([HAVE_AARCH64_CRC32], [1],
    [Define to 1 when aarch64 CRC32 API is available.])])

dnl Check for asm goto support.
AC_CACHE_CHECK([for asm goto], [php_cv_have__asm_goto],
[AC_LINK_IFELSE([AC_LANG_PROGRAM([], [
#if defined(__x86_64__) || defined(__i386__)
  __asm__ goto("jmp %l0\n" :::: end);
#elif defined(__aarch64__)
  __asm__ goto("b %l0\n" :::: end);
#endif
end:
  return 0;
])],
[php_cv_have__asm_goto=yes],
[php_cv_have__asm_goto=no])])
AS_VAR_IF([php_cv_have__asm_goto], [yes],
  [AC_DEFINE([HAVE_ASM_GOTO], [1],
    [Define to 1 if asm goto support is available.])])

dnl Check Valgrind support.
PHP_ARG_WITH([valgrind],
  [whether to enable Valgrind support],
  [AS_HELP_STRING([--with-valgrind],
    [Enable Valgrind support])],
  [no],
  [no])

AS_VAR_IF([PHP_VALGRIND], [no],, [
  PKG_CHECK_MODULES([VALGRIND], [valgrind],
     [PHP_EVAL_INCLINE([$VALGRIND_CFLAGS])
       AC_DEFINE([HAVE_VALGRIND], [1],
        [Define to 1 if Valgrind is enabled and supported.])])
  save_CFLAGS=$CFLAGS
  CFLAGS="$CFLAGS $VALGRIND_CFLAGS"
  AC_CHECK_HEADERS([valgrind/cachegrind.h])
  CFLAGS=$save_CFLAGS
])

dnl General settings.
dnl ----------------------------------------------------------------------------
PHP_CONFIGURE_PART([General settings])

PHP_HELP_SEPARATOR([General settings:])

PHP_ARG_ENABLE([gcov],
  [whether to include gcov symbols],
  [AS_HELP_STRING([--enable-gcov],
    [Enable GCOV code coverage - FOR DEVELOPERS ONLY!!])],
  [no],
  [no])

AS_VAR_IF([PHP_GCOV], [yes], [
  AS_VAR_IF([GCC], [yes],,
    [AC_MSG_ERROR([GNU C compatible compiler is required for --enable-gcov])])

  dnl Check if ccache is being used.
  AS_CASE([$($php_shtool path $CC)],
    [*ccache*], [gcc_ccache=yes],
    [gcc_ccache=no])

  if test "$gcc_ccache" = "yes" && (test -z "$CCACHE_DISABLE" || test "$CCACHE_DISABLE" != "1"); then
    AC_MSG_ERROR(m4_text_wrap([
      ccache must be disabled when --enable-gcov option is used. You can disable
      ccache by setting environment variable CCACHE_DISABLE=1.
    ]))
  fi

  AC_DEFINE([HAVE_GCOV], [1], [Define to 1 if GCOV code coverage is enabled.])
  PHP_ADD_MAKEFILE_FRAGMENT([$abs_srcdir/build/Makefile.gcov], [$abs_srcdir])

  dnl Remove all optimization flags from CFLAGS.
  PHP_REMOVE_OPTIMIZATION_FLAGS

  dnl Add the special gcc flags.
  CFLAGS="$CFLAGS -O0 -fprofile-arcs -ftest-coverage"
  CXXFLAGS="$CXXFLAGS -O0 -fprofile-arcs -ftest-coverage"
])

PHP_ARG_ENABLE([debug],
  [whether to include debugging symbols],
  [AS_HELP_STRING([--enable-debug],
    [Compile with debugging symbols])],
  [no],
  [no])

AS_VAR_IF([PHP_DEBUG], [yes], [
  PHP_DEBUG=1
  ZEND_DEBUG=yes
  CFLAGS="$CFLAGS -UNDEBUG"
  CXXFLAGS="$CXXFLAGS -UNDEBUG"
  PHP_REMOVE_OPTIMIZATION_FLAGS
  dnl Add -O0 only if GCC or ICC is used.
  if test "$GCC" = "yes" || test "$ICC" = "yes"; then
    CFLAGS="$CFLAGS -O0"
    CXXFLAGS="$CXXFLAGS -g -O0"
  fi
  if test "$SUNCC" = "yes"; then
    if test -n "$auto_cflags"; then
      CFLAGS="-g"
      CXXFLAGS="-g"
    else
      CFLAGS="$CFLAGS -g"
      CXXFLAGS="$CFLAGS -g"
    fi
  fi
], [
  PHP_DEBUG=0
  ZEND_DEBUG=no
  dnl Moderate optimization for BLOA production builds
  dnl LTO and aggressive optimizations are added to LDFLAGS and handled by Make
  dnl to avoid linker plugin issues during configure tests
  CFLAGS="$CFLAGS -DNDEBUG -O2"
  CXXFLAGS="$CXXFLAGS -DNDEBUG -O2"
])

PHP_ARG_ENABLE([debug-assertions],
  [whether to enable debug assertions in release mode],
  [AS_HELP_STRING([--enable-debug-assertions],
    [Compile with debug assertions even in release mode])],
  [no],
  [no])

AS_VAR_IF([PHP_DEBUG_ASSERTIONS], [yes], [
  PHP_DEBUG=1
  ZEND_DEBUG=yes
  CFLAGS="$CFLAGS -UNDEBUG"
  CXXFLAGS="$CXXFLAGS -UNDEBUG"
])

AC_ARG_ENABLE([zts],
  [AS_HELP_STRING([--enable-zts],
    [Enable thread safety])],
  [ZEND_ZTS=$enableval],
  [ZEND_ZTS=yes])

AS_VAR_IF([ZEND_ZTS], [yes], [PHP_THREAD_SAFETY=yes], [PHP_THREAD_SAFETY=no])

AS_VAR_IF([PHP_THREAD_SAFETY], [yes], [
  AS_VAR_IF([pthreads_working], [yes], [],
    [AC_MSG_FAILURE(m4_text_wrap([
      Unable to verify system support for POSIX Threads, which are required for
      PHP thread safety (ZTS) build.
    ]))])

  AC_MSG_CHECKING([for POSIX threads])
  AC_MSG_RESULT([yes])
])

PHP_ARG_ENABLE([rtld-now],
  [whether to dlopen extensions with RTLD_NOW instead of RTLD_LAZY],
  [AS_HELP_STRING([--enable-rtld-now],
    [Use dlopen with RTLD_NOW instead of RTLD_LAZY])],
  [no],
  [no])

AS_VAR_IF([PHP_RTLD_NOW], [yes],
  [AC_DEFINE([PHP_USE_RTLD_NOW], [1],
    [Define to 1 if 'dlopen()' uses the 'RTLD_NOW' mode flag instead of
    'RTLD_LAZY'.])])

PHP_ARG_WITH([layout],
  [layout of installed files],
  [AS_HELP_STRING([--with-layout=TYPE],
    [Set how installed files will be laid out. Type can be either PHP or GNU [PHP]])],
  [PHP],
  [no])

AS_CASE([$PHP_LAYOUT], [GNU], [oldstyleextdir=no], [oldstyleextdir=yes])

PHP_ARG_WITH([config-file-path],
  [path to configuration file],
  [AS_HELP_STRING([--with-config-file-path=PATH],
    [Set the path in which to look for php.ini [PREFIX/lib]])],
  [DEFAULT],
  [no])

AS_VAR_IF([PHP_CONFIG_FILE_PATH], [DEFAULT],
  [AS_CASE([$PHP_LAYOUT],
    [GNU], [PHP_CONFIG_FILE_PATH=$sysconfdir],
    [PHP_CONFIG_FILE_PATH=$libdir])])

AC_MSG_CHECKING([where to scan for configuration files])
PHP_ARG_WITH([config-file-scan-dir],,
  [AS_HELP_STRING([--with-config-file-scan-dir=PATH],
    [Set the path where to scan for configuration files])],
  [DEFAULT],
  [no])

AS_VAR_IF([PHP_CONFIG_FILE_SCAN_DIR], [DEFAULT], [PHP_CONFIG_FILE_SCAN_DIR=])
AC_MSG_RESULT([$PHP_CONFIG_FILE_SCAN_DIR])

PHP_ARG_ENABLE([sigchild],
  [whether to enable PHP's own SIGCHLD handler],
  [AS_HELP_STRING([--enable-sigchild],
    [Enable PHP's own SIGCHLD handler])],
  [no],
  [no])

AH_TEMPLATE([PHP_SIGCHILD],
  [Define to 1 if PHP uses its own SIGCHLD handler, and to 0 if not.])
AS_VAR_IF([PHP_SIGCHILD], [yes],
  [AC_DEFINE([PHP_SIGCHILD], [1])],
  [AC_DEFINE([PHP_SIGCHILD], [0])])

PHP_ARG_ENABLE([libgcc],
  [whether to explicitly link against libgcc],
  [AS_HELP_STRING([--enable-libgcc],
    [Enable explicitly linking against libgcc])],
  [no],
  [no])

AS_VAR_IF([PHP_LIBGCC], [yes], [
  PHP_LIBGCC_LIBPATH([gcc])
  AS_VAR_IF([libgcc_libpath],,
    [AC_MSG_ERROR([Cannot locate libgcc. Make sure that gcc is in your path])])
  PHP_ADD_LIBPATH([$libgcc_libpath])
  PHP_ADD_LIBRARY([gcc], [yes])
])

PHP_ARG_ENABLE([short-tags],
  [whether to enable short tags by default],
  [AS_HELP_STRING([--disable-short-tags],
    [Disable the short-form <? start tag by default])],
  [yes],
  [no])

AH_TEMPLATE([DEFAULT_SHORT_OPEN_TAG],
  [Define to string "1" if PHP short open tags '<?' are enabled by default, and
  to string "0" if they are not.])
AS_VAR_IF([PHP_SHORT_TAGS], [yes],
  [AC_DEFINE([DEFAULT_SHORT_OPEN_TAG], ["1"])],
  [AC_DEFINE([DEFAULT_SHORT_OPEN_TAG], ["0"])])

PHP_ARG_ENABLE([dmalloc],
  [whether to enable dmalloc],
  [AS_HELP_STRING([--enable-dmalloc],
    [Enable dmalloc])],
  [no],
  [no])

AS_VAR_IF([PHP_DMALLOC], [yes],
  [AC_CHECK_LIB([dmalloc], [dmalloc_error],
    [PHP_ADD_LIBRARY([dmalloc])
      AC_DEFINE([HAVE_DMALLOC], [1], [Define to 1 if you have dmalloc.])
      AS_VAR_APPEND([CPPFLAGS], [" -DDMALLOC_FUNC_CHECK"])],
    [AC_MSG_FAILURE([The dmalloc check failed. Cannot enable dmalloc.])])])

PHP_ARG_ENABLE([ipv6],
