name: BLOA CI

on: [push, pull_request]

jobs:
  test_bloa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build BLOA interpreter
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential libcurl4-openssl-dev libsqlite3-dev
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBLOA_USE_MYSQL=OFF
          cmake --build build -- -j$(nproc)

      - name: Run BLOA tests
        run: |
          ./build/bloa tests/test_json
          ./build/bloa tests/test_csv
          ./build/bloa tests/test_misc
